### ISSUE TITLE
Not working on linux  ( at least not flatpaks )

### ISSUE THREAD

**Issue by sfjohansson** [Maligan/unity-zed#1]
Flathub is very popular for installing apps on linux: https://flathub.org/apps/dev.zed.Zed

**Comment by Maligan** [comment]
Thank you for report, will try reproduce on virtual machine :-)

**Comment by sfjohansson** [comment]
I'd be happy to help, I'd assume it might just be just the discovering of zed here:

```c#
    public class ZedDiscovery
    {
        public CodeEditor.Installation[] GetInstallations()
        {
            var results = new List<CodeEditor.Installation>();

            var candidates = new NPath[] {
                new ("/Applications/Zed.app/Contents/MacOS/cli"),
                new ("/usr/local/bin/zed"),
            };
```

**Comment by Maligan** [comment]
Does flatpak have a default installation places? In cases for per-user installation and per-machine installation?

As I see there are a system-wide `/var/lib/flatpak/` and user-wide `~/.var/app/` but I have to check them to be sure...

**Comment by sfjohansson** [comment]
you can actually use the terminal command to get app information

```bash
flatpak info dev.zed.Zed


Zed - High-performance code editor

          ID: dev.zed.Zed
         Ref: app/dev.zed.Zed/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v0.152.4
     License: AGPL-3.0-or-later and Apache-2.0 and GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 151.4 MB
     Runtime: org.freedesktop.Sdk/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: dcc8eb5b199d9ca6d79e172875f8a110522273c2b17608a3ffcd4fd38905e41d
      Parent: f98817c43cb5131a2c7649668c8643ae423f067fdf381275b0982e126563ea29
     Subject: Update to v0.152.4 (#18) (27de1768)
        Date: 2024-09-17 01:57:14 +0000

```

and 

```bash
~  flatpak info --show-location dev.zed.Zed                                                                                                                                                                                                                                                                                                                                                                                                                              INT ✘  12:27:31 
/var/lib/flatpak/app/dev.zed.Zed/x86_64/stable/dcc8eb5b199d9ca6d79e172875f8a110522273c2b17608a3ffcd4fd38905e41d

```

**Comment by Maligan** [comment]
Yes, I did try this way but it has several cons:
- Unity call this method to discovery too often in UI thread, so asking for shell execute cause hard freezing
- There is no guarantee that flatpak is exposed to Unity $PATH (for Mac there is such a problem) so I have to discovery flatpak itself before using it :-(

Anyway I didn't add default [installation paths](https://zed.dev/docs/linux) for Linux/Windows and will try them at the first step, If this doesn't help I will add custom GUI into Preference tab.

**Comment by sfjohansson** [comment]
just checking it on startup and save it somewhere could be an option:


```
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
public static class EditorStartup
{
    public static string pathExternalEditor;

    // Static constructor
    static EditorStartup()
    {
        // This code will run when the editor loads
        pathExternalEditor = "Editor Loaded at: " + System.DateTime.Now;
        Debug.Log("Editor has started. Static string saved: " + myStaticString);
    }
}

```

**Comment by sfjohansson** [comment]
I just tested the `0.2.1` Release and my flatpak installation is discovered. I can select it and it will open scripts in Zed.

Should the csharp solution work fully, ie going to implementations of this or that, finding usages etc?

**Comment by Maligan** [comment]
Oh, thank you I implement only discovering of system installation of Zed will do it for userwide!

Zed use C# language server via omnisharp https://zed.dev/docs/languages/csharp

It works perfect for small-to-medium pet project of mine, but crashes when I try to start my huge working project ~ 160 asmdef etc. 3GB of RAM usages.

I check the status of omnisharp via task manager and it really has some problems.

Unfortunately it's a Zed's problem. Maybe I can tweak some behaviors with changing workdir settings but I can't find omnisharp integration docs / configuration which can help with that.

**Comment by sfjohansson** [comment]
Probably not many that uses Zed for C# at this point...well   I'd say that the issue of discovering Zed is resolved! :)
